### ISSUE TITLE
invalid operation in attempts to upgrade to core profile 330

### ISSUE THREAD

**Issue by autosquid** [glumpy/glumpy#102]
This is what happened after fixes I described in https://github.com/glumpy/glumpy/issues/79 

My test code is based on https://github.com/glumpy/glumpy/blob/master/examples/app-two-programs.py

```
import numpy as np
from glumpy import gl, app, gloo


app.use("sdl2", api='GL', major=3, minor=3,profile='core')
config = app.configuration.Configuration()

config.major_version = 3
config.minor_version = 3
config.profile = "core"
window = app.Window(config=config, width=500, height=300)

vertex = """#version 330
in vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0.0, 1.0);
    gl_PointSize = 30.0;
}
"""

fragment1 = """#version 330
out vec4 FragColor;
void main() {
    FragColor = vec4(0.0, 0.0, 1.0, 1.0);
}
"""



fragment2 = """
void main() {
    gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
}
"""


program1 = gloo.Program(vertex, fragment1)  # blue on the right
program1['a_position'] = np.zeros((1,2),dtype=np.float32) + 0.5
program2 = gloo.Program(vertex, fragment2)  # red on the left
program2['a_position'] = np.zeros((1,2),dtype=np.float32) - 0.5


@window.event
def on_draw(dt):
    window.clear()
    program1.draw(gl.GL_POINTS)
    program2.draw(gl.GL_POINTS)

app.run()
```

The output and reported error is:

```
i] Using SDL2 (GL 4.1)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "test_glumpy.py", line 54, in <module>
    app.run()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/__init__.py", line 302, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/__init__.py", line 262, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/window/window.py", line 219, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "test_glumpy.py", line 51, in on_draw
    program1.draw(gl.GL_POINTS)
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/gloo/program.py", line 592, in draw
    self.activate()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/gloo/globject.py", line 89, in activate
    self._activate()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/gloo/program.py", line 385, in _activate
    attribute.activate()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/gloo/globject.py", line 89, in activate
    self._activate()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/gloo/variable.py", line 380, in _activate
    gl.glEnableVertexAttribArray(self.handle)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = 'invalid operation',
	baseOperation = glEnableVertexAttribArray,
	cArguments = (0,)
)
```

**Comment by rougier** [comment]
Did you check I do not remove automatically the version information?

**Comment by autosquid** [comment]
I removed the "#version 120" thing from (maybe) shader.py(?), and add version information directly in shader source code.

**Comment by rougier** [comment]
So maybe the `glEnableVertexAttribArray` is deprecated. Can you use the forward compatibility instead and check it solves the problem ?

**Comment by autosquid** [comment]
```
[w] Cannot bind framebuffer
[w] Cannot read RED channel size from the framebuffer
[w] Cannot read GREEN channel size from the framebuffer
[w] Cannot read BLUE channel size from the framebuffer
[w] Cannot read ALPHA channel size from the framebuffer
[w] Cannot read DEPTH size from the framebuffer
[w] Cannot read STENCIL size from the framebuffer
[w] Cannot read sRGB value from the framebuffer
None
Traceback (most recent call last):
  File "test_glumpy.py", line 17, in <module>
    window = app.Window(config=config, width=500, height=300)
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/__init__.py", line 186, in __new__
    config = configuration.gl_get_configuration()
  File "/Users/uuplusu/.virtualenvs/mpy27/lib/python2.7/site-packages/glumpy/app/configuration.py", line 364, in gl_get_configuration
    version = version.split(" ")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

No luck, sadly.

Fail to get gl version (which maybe a glew bug on osx).

**Comment by rougier** [comment]
Ok, I'll investigate further. Don't hesitate to ask for update on this thread.

**Comment by yuyu2172** [comment]
I observed the same error.
The error raises error code 1282, which is telling us that VAO needs to be initialized.
I modified the code to initialize a VAO, and the shaders run with version 3.3 with core mode.

```python
# modified examples/tutorial/quad-simple.py
from glumpy import app, gloo, gl

vertex = """
  uniform float scale;
  attribute vec2 position;
  attribute vec4 color;
  varying vec4 v_color;
  void main()
  {
    gl_Position = vec4(scale*position, 0.0, 1.0);
    v_color = color;
  } """

fragment = """
  varying vec4 v_color;
  void main()
  {
      gl_FragColor = v_color;
  } """

app.use('glfw', api='GL', major=3, minor=3, profile='core')

# Create a window with a valid GL context
window = app.Window()

vao = gl.glGenVertexArrays(1)
gl.glBindVertexArray(vao)

# Build the program and corresponding buffers (with 4 vertices)
quad = gloo.Program(vertex, fragment, count=4)

# Upload data into GPU
quad['color'] = [ (1,0,0,1), (0,1,0,1), (0,0,1,1), (1,1,0,1) ]
quad['position'] = [ (-1,-1),   (-1,+1),   (+1,-1),   (+1,+1)   ]
quad['scale'] = 1.0


# Tell glumpy what needs to be done at each redraw
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

# Run the app
app.run()
```

**Comment by rougier** [comment]
I'm  lost. You created a vertex array that you don't use and it works?

**Comment by yuyu2172** [comment]
I never unbineded the VAO, so it should work.
This is hacky, and I am not sure if this is reliable in other situations.
I just found that ther eis `glumpy.gloo.VertexArray`. I should probably use this to interact with array objects.

**Comment by yuyu2172** [comment]
Here is a script using `VertexArray`.

```python
# modified examples/tutorial/quad-simple.py
from glumpy import app, gloo, gl
import numpy as np

vertex = """
  uniform float scale;
  attribute vec2 position;
  attribute vec4 color;
  varying vec4 v_color;
  void main()
  {
    gl_Position = vec4(scale*position, 0.0, 1.0);
    v_color = color;
  } """

fragment = """
  varying vec4 v_color;
  void main()
  {
      gl_FragColor = v_color;
  } """

app.use('glfw', api='GL', major=3, minor=3, profile='core')

# Create a window with a valid GL context
window = app.Window()

# Build the program and corresponding buffers (with 4 vertices)
quad = gloo.Program(vertex, fragment, count=4)
dtype = [('color', np.float32, 4),
         ('position', np.float32, 2)]
quad_arrays = np.zeros(4, dtype).view(gloo.VertexArray)
# Upload data into GPU
quad_arrays['color'] = [ (1,0,0,1), (0,1,0,1), (0,0,1,1), (1,1,0,1) ]
quad_arrays['position'] = [ (-1,-1),   (-1,+1),   (+1,-1),   (+1,+1)   ]
quad.bind(quad_arrays)

quad['scale'] = 1.0


# Tell glumpy what needs to be done at each redraw
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

# Run the app
app.run()
```

**Comment by rougier** [comment]
It would be worth adding this example in the examples directory. Also, coudl you check that you're able to create at least two different vertex arrays? (to check everything is handled properly)

**Comment by yuyu2172** [comment]
Hi. Sorry for the late reply.

I made an example with two different vertex arrays.
The program switches between two programs with different VAOs every one second.

```python
# modified examples/tutorial/quad-simple.py
from glumpy import app, gloo, gl
import numpy as np

vertex = """
  uniform float scale;
  attribute vec2 position;
  attribute vec4 color;
  varying vec4 v_color;
  void main()
  {
    gl_Position = vec4(scale*position, 0.0, 1.0);
    v_color = color;
  } """

fragment = """
  varying vec4 v_color;
  void main()
  {
      gl_FragColor = v_color;
  } """

app.use('glfw', api='GL', major=3, minor=3, profile='core')

# Create a window with a valid GL context
window = app.Window()

# Build the program and corresponding buffers (with 4 vertices)
quad_0 = gloo.Program(vertex, fragment, count=4)
dtype = [('color', np.float32, 4),
         ('position', np.float32, 2)]
quad_arrays_0 = np.zeros(4, dtype).view(gloo.VertexArray)
# all black
quad_arrays_0['color'] = [ (0,0,0,1), (0,0,0,1), (0,0,0,1), (0,0,0,1) ]
quad_arrays_0['position'] = [ (-1,-1),   (-1,+1),   (+1,-1),   (+1,+1)   ]
quad_0.bind(quad_arrays_0)

quad_1 = gloo.Program(vertex, fragment, count=4)
dtype = [('color', np.float32, 4),
         ('position', np.float32, 2)]
quad_arrays_1 = np.zeros(4, dtype).view(gloo.VertexArray)
# Upload data into GPU
quad_arrays_1['color'] = [ (1,0,0,1), (0,1,0,1), (0,0,1,1), (1,1,0,1) ]
quad_arrays_1['position'] = [ (-1,-1),   (-1,+1),   (+1,-1),   (+1,+1)   ]
quad_1.bind(quad_arrays_1)

quad_0['scale'] = 1
quad_1['scale'] = 1


# Tell glumpy what needs to be done at each redraw
count = 0
@window.event
def on_draw(dt):
    global count
    window.clear()
    if count % 2 == 0:
        quad_0.draw(gl.GL_TRIANGLE_STRIP)
    else:
        quad_1.draw(gl.GL_TRIANGLE_STRIP)
    count += 1

# Run the app with fps=1
app.run(framerate=1)
```

I could not figure out how to register more than one VAOs to a program.
Do you know how to do this?

**Comment by rougier** [comment]
Thanks. I'm not sure I understand your question. In your example, you have two vertex arrays, haven't you?

**Comment by yuyu2172** [comment]
Oh sorry for confusing you.
I could not figure out how to switch between VAOs using a single program.
In my example, I used two programs, and each VAO is registered to one of them.

**Comment by rougier** [comment]
I think you can use `quad.bind(quad_arrays_0)` and `quad.bind(quad_arrays_1)`, no?

**Comment by yuyu2172** [comment]
You are right. I can use `Program.bind` to switch between VAOs. Thanks!

**Comment by rougier** [comment]
Would you mind making a PR from your (corrected) example to add it to the examples? If you have an idea of a better way to illustrate the use of VBO, it would be all the best, but even your example as it is would be useful. Maybe a proper name for the example would be useful as well.

**Comment by yuyu2172** [comment]
Actually, my previous comment was wrong. It did not work. I got confused because I checked an example that alternates between two colors that are not the backgroudn color, and it failed to work.

Please check this PR, which fixes the problem I found.
https://github.com/glumpy/glumpy/pull/137

**Comment by rougier** [comment]
Thanks, just merged the PR.
