### ISSUE TITLE
Earth.py fails again in Ubuntu 16.04

### ISSUE THREAD

**Issue by cycleuser** [glumpy/glumpy#106]
Under 3.6:
```Bash
i@pc:~/glumpy/examples$ python earth.py
Traceback (most recent call last):
  File "earth.py", line 159, in <module>
    labels.append(C[i], font, origin = P[i])
  File "/home/i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glumpy/graphics/collections/agg_glyph_collection.py", line 75, in append
    V, I = self.bake(text, font, anchor_x, anchor_y)
  File "/home/i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glumpy/graphics/collections/agg_glyph_collection.py", line 127, in bake
    glyph = font[charcode]
  File "/home/i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glumpy/graphics/text/agg_font.py", line 32, in __getitem__
    self.load('%c' % charcode)
  File "/home/i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glumpy/graphics/text/agg_font.py", line 82, in load
    texture = self.atlas[y:y+h,x:x+w]
  File "/home/i/.pyenv/versions/3.6.0/lib/python3.6/site-packages/glumpy/gloo/gpudata.py", line 116, in __getitem__
    Z = np.ndarray.__getitem__(self, key)
TypeError: slice indices must be integers or None or have an __index__ method

```

3.5.2:
```
i@pc:~/glumpy/examples$ python earth.py
[i] Requesting "earth-black.jpg" from remote server
[w] Data not available on remote server
Traceback (most recent call last):
  File "earth.py", line 61, in <module>
    earth['texture'] = data.get("earth-black.jpg")
  File "/home/i/.pyenv/versions/3.5.2/lib/python3.5/site-packages/glumpy-1.0.6-py3.5-linux-x86_64.egg/glumpy/data/__init__.py", line 163, in get
    return load(filename, *args, **kwargs)
  File "/home/i/.pyenv/versions/3.5.2/lib/python3.5/site-packages/glumpy-1.0.6-py3.5-linux-x86_64.egg/glumpy/data/__init__.py", line 169, in load
    extension = os.path.basename(filename).split('.')[-1]
  File "/home/i/.pyenv/versions/3.5.2/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

I have already change Arcball to Trackball, still not working, some other places need to be altered?

**Comment by rougier** [comment]
I think the problem comes from a (lacking) explocit cast of index into in for numpy. In `gpudata.py`, the key  (each component) must be converted into in int.

**Comment by cycleuser** [comment]
@rougier 

This same file cloned from glumpy git works well under macOS 10.12 with 3.5.2.
That makes me puzzled about what should be done to solve it.
Maybe I can only move on and try some others.

**Comment by rougier** [comment]
I think it depends on the numpy version you're using.

**Comment by cycleuser** [comment]
@rougier 

 That is possible. 
macOS 10.12 is using '1.10.4' but the Ubuntu machine use '1.12.0'

**Comment by rougier** [comment]
Recent numpy is less tolerant with implicit type casting.

**Comment by cycleuser** [comment]
Use numpy 1.10.4 fixed the problem ~~ Close it now~
