### ISSUE TITLE
1.0.6 some current examples not executing

### ISSUE THREAD

**Issue by WalterZimmer** [glumpy/glumpy#109]
Hi, this is really great stuff!!!

While playing around with the gallery codes, just noticed some issues:
- cartopy, mandelbrot, voronoi and fireworks work great!
- earth.py: ImportError: cannot import name 'Arcball'
- topojson[-picking].py, spiral.py, lorenz.py:
  File "/usr/lib64/python3.4/site-packages/glumpy/graphics/collections/base_collection.py", line 517, in _update
    texture = texture.reshape(shape[0],shape[1],4)
  TypeError: 'float' object cannot be interpreted as an integer

Overall goal is to draw earth with country boundaries (as in earth.py) with high quality antialiased lines (as in spiral.py) and picking support.

OpenSuse Leap 42.2, kernel 4.4.57 64bit, stock Python 3.4.5
- pyopengl 3.1.0, Cython 0.24, GLFW 3.1.2 via Opensuse repo
- Glumpy 1.0.6 installed via pip3 (which pulled in numpy 1.12.1 and triangle 20170106)

Any advice or pointers where I should look at? Can I debug to get better error messages? Or did I do anything wrong with the install?
Many thanks!

**Comment by rougier** [comment]
For the earth.py, I think I forgot to push the arcbal commit.
For the second error, it's probably numpy complaining about type error. a reshape(int(shape[0]), int(shape[1]),4) should fix it.

Did you use latest version ?

**Comment by WalterZimmer** [comment]
I used latest "official" version 1.0.6 installed via pip3, not the latest from git.

The reshape you suggested applied to glumpy/graphics/collections/base_collection.py:562 fixes it indeed. Now I can play some more, thanks!

**Comment by WalterZimmer** [comment]
If I wrap the usage of self._padding in glumpy/graphics/text/sdf_font.py lines 100, 101 and 103 in int(), the lorenz.py also works.

**Comment by WalterZimmer** [comment]
Also, an int() around "len(V)/2" in glumpy/graphics/collections/agg_fast_path_collection.py line 169 makes spiral.py and collection-triangles.py run.

**Comment by WalterZimmer** [comment]
All right, I upgraded to the current git version. All issues above are fixed there!

Only one minor font issue, triggered by earth.py:
Traceback (most recent call last):
  File "earth.py", line 157, in <module>
    font = FontManager.get("OpenSans-Regular.ttf", size=16, mode='agg')
  File "/usr/lib64/python3.4/site-packages/glumpy-1.0.6-py3.4-linux-x86_64.egg/glumpy/graphics/text/font_manager.py", line 73, in get
    cache[key] = AggFont(filename, size, atlas)
  File "/usr/lib64/python3.4/site-packages/glumpy-1.0.6-py3.4-linux-x86_64.egg/glumpy/graphics/text/agg_font.py", line 27, in __init__
    freetype.set_lcd_filter(freetype.FT_LCD_FILTER_LIGHT)
  File "/usr/lib64/python3.4/site-packages/glumpy-1.0.6-py3.4-linux-x86_64.egg/glumpy/ext/freetype/__init__.py", line 217, in set_lcd_filter
    if error: raise FT_Exception(error)
glumpy.ext.freetype.ft_errors.FT_Exception: FT_Exception:  (unimplemented feature)

My (Opensuse provided) Freetype version is 2.6.3.

So I just uncommented the set_lcd_filter() and it works. Exactly what we need - thanks!!!

**Comment by rougier** [comment]
The LCD filter depends on the option you've been usigin when compiling freetype. If it's a system installation, most likely it has been disabled because of patent problem. But you can fix that by installing from sources with the right option checked.
