### ISSUE TITLE
Shader compilation error

### ISSUE THREAD

**Issue by Jankd** [glumpy/glumpy#114]
I can't figure out what is going on here:

Traceback (most recent call last):
  File "D:/GoogleDrive/Thesis/Python/tteeee.py", line 19, in <module>
    app.run()
  File "C:\Python27\lib\site-packages\glumpy\app\__init__.py", line 302, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "C:\Python27\lib\site-packages\glumpy\app\__init__.py", line 262, in __init__
Error in Vertex shader 2 (<string>)
 -> error C0118: macros prefixed with '__' are reserved
()
 ...
 059 #ifndef __GEO_POSITION_STRUCT__
 060 #define __GEO_POSITION_STRUCT__
 061 struct GeoPosition
 062 {
 063     float longitude;
 ...
()
    window.dispatch_event('on_resize', window._width, window._height)
  File "C:\Python27\lib\site-packages\glumpy\app\window\event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Python27\lib\site-packages\glumpy\app\window\window.py", line 219, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "C:\Python27\lib\site-packages\glumpy\app\window\event.py", line 384, in dispatch_event
    if handler(*args):
  File "D:/GoogleDrive/Thesis/Python/tteeee.py", line 11, in on_draw
    points.draw()
  File "C:\Python27\lib\site-packages\glumpy\graphics\collections\collection.py", line 209, in draw
    program.draw(mode)
  File "C:\Python27\lib\site-packages\glumpy\gloo\program.py", line 592, in draw
    self.activate()
  File "C:\Python27\lib\site-packages\glumpy\gloo\globject.py", line 86, in activate
    self._create()
  File "C:\Python27\lib\site-packages\glumpy\gloo\program.py", line 175, in _create
    self._build_shaders(self._handle)
  File "C:\Python27\lib\site-packages\glumpy\gloo\program.py", line 223, in _build_shaders
    shader.activate()
  File "C:\Python27\lib\site-packages\glumpy\gloo\globject.py", line 96, in activate
    self._update()
  File "C:\Python27\lib\site-packages\glumpy\gloo\shader.py", line 242, in _update
    raise RuntimeError("Shader compilation error")
RuntimeError: Shader compilation error

**Comment by rougier** [comment]
What version of glumpy are you using ? I think the shader compiler complains about some variables that start with `__` but I can't find any in the glumpy/glumpy/library.

**Comment by rreno** [comment]
I think I have a related bug.
I purposefully left off a semicolon in the fragment shader and got the following:

Error in Fragment shader 3 (<string>)
 -> preprocessor warning: Macro names containing "__" are reserved for use by the implementation.

 000 #define _GLUMPY__FRAGMENT_SHADER__
 001 // --- Snippets code : start --- //
 002 // --- Snippets code : end --- //
 ...

Traceback (most recent call last):
...

The Shader class method _parse_error is finding the wrong line in the return value of glGetShaderInfoLog().  When I add print(error) before passing the error to _parse_error()  and print(lineno); print(mesg) after returning from the method I get:

0:2(9): preprocessor warning: Macro names containing "__" are reserved for use by the implementation.

0:11(1): error: syntax error, unexpected '}', expecting ',' or ';'

2
preprocessor warning: Macro names containing "__" are reserved for use by the implementation.
Error in Fragment shader 3 (<string>)
 -> preprocessor warning: Macro names containing "__" are reserved for use by the implementation.

 000 #define _GLUMPY__FRAGMENT_SHADER__
 001 // --- Snippets code : start --- //
 002 // --- Snippets code : end --- //
 ...

Traceback (most recent call last):
...
So it looks like the preprocessor warning is polluting the error messages. I'm putting together a PR that changes the #define's to have only single underscores. After doing that, the proper error message shows up and it prints the context from the offending shader.

**Comment by rougier** [comment]
Thanks !
