### ISSUE TITLE
Problem with fonts on Windows and TypeError: 'float' 

### ISSUE THREAD

**Issue by shoshia** [glumpy/glumpy#124]
setup:
Windows 10  64 bit...
This is an output:

c:\Users\levan\Desktop\glumpy-master\examples>
c:\Users\levan\Desktop\glumpy-master\examples>python lorenz.py
[i] Using GLFW (GL 4.6)
[i] Requesting "OpenSans-Regular.ttf" from remote server
[w] Data not available on remote server
[w] Falling back to default font
[i] Requesting "OpenSans-Bold.ttf" from remote server
[w] Data not available on remote server
[w] Falling back to default font
Traceback (most recent call last):
  File "lorenz.py", line 59, in <module>
    anchor_x = "left", anchor_y = "center")
  File "C:\Python36\lib\site-packages\glumpy\graphics\collections\sdf_glyph_collection.py", line 76, in append
    V, I = self.bake(text, font, anchor_x, anchor_y)
  File "C:\Python36\lib\site-packages\glumpy\graphics\collections\sdf_glyph_collection.py", line 128, in bake
    glyph = font[charcode]
  File "C:\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 75, in __getitem__
    self.load('%c' % charcode)
  File "C:\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 130, in load
    data,offset,advance = self.load_glyph(face, charcode)
  File "C:\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 102, in load_glyph
    hires_data = np.zeros( (hires_height,hires_width), np.double)
TypeError: 'float' object cannot be interpreted as an integer

c:\Users\levan\Desktop\glumpy-master\examples>

**Comment by rougier** [comment]
I think tit should be `hires_data = np.zeros( (int(hires_height),int(hires_width)), np.double)`

**Comment by rougier** [comment]
Also, can you check in `glumpy/data` if the font has been actually downloaded ?

**Comment by shoshia** [comment]
I downloaded master branch and did install manually ...works fine..thank you.
