### ISSUE TITLE
ModuleNotFoundError: No module named 'glumpy.ext.sdf.sdf'

### ISSUE THREAD

**Issue by Axel1492** [glumpy/glumpy#149]
when trying to run `examples/font-sdf.py`:

```
Traceback (most recent call last):
  File ".\Graph.py", line 26, in <module>
    labels.append(text, regular, origin = (x,y,z), scale=scale, anchor_x="left")
  File "C:\python\Python36\lib\site-packages\glumpy\graphics\collections\sdf_glyph_collection.py", line 76, in append
    V, I = self.bake(text, font, anchor_x, anchor_y)
  File "C:\python\Python36\lib\site-packages\glumpy\graphics\collections\sdf_glyph_collection.py", line 128, in bake
    glyph = font[charcode]
  File "C:\python\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 75, in __getitem__
    self.load('%c' % charcode)
  File "C:\python\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 130, in load
    data,offset,advance = self.load_glyph(face, charcode)
  File "C:\python\Python36\lib\site-packages\glumpy\graphics\text\sdf_font.py", line 82, in load_glyph
    from glumpy.ext.sdf import compute_sdf
  File "C:\python\Python36\lib\site-packages\glumpy\ext\sdf\__init__.py", line 5, in <module>
    from .sdf import *
ModuleNotFoundError: No module named 'glumpy.ext.sdf.sdf'
```

**Comment by rougier** [comment]
This has been fixed on GitHub but not on pip. We need a new release soon.
