### ISSUE TITLE
glumpy\\app\\window\\backends\\backend_glfw.py'>) not available

### ISSUE THREAD

**Issue by jeff5048** [glumpy/glumpy#157]
It looks like the backend module loader in glumpy\app\__init__.py is not working around line 116.  Why is that?

Windows 10 Pro
64 bit OS and processor

Original Page Code:

from glumpy import app, gloo, gl

vertex = """
    attribute vec2 position;
    void main(){ gl_Position = vec4(position, 0.0, 1.0); } """

fragment = """
    void main() { gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); } """

# Create a window with a valid GL context
window = app.Window()

# Build the program and corresponding buffers (with 4 vertices)
quad = gloo.Program(vertex, fragment, count=4)

# Upload data into GPU
quad['position'] = (-1,+1), (+1,+1), (-1,-1), (+1,-1)

# Tell glumpy what needs to be done at each redraw
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

# Run the app
app.run()

Error:
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:\Users\jeff5\Desktop\Python\OpenGL_Exercises\Example1.py ====
[w] Backend (<module 'glumpy.app.window.backends.backend_glfw' from 'C:\\Users\\jeff5\\AppData\\Roaming\\Python\\Python36\\site-packages\\glumpy\\app\\window\\backends\\backend_glfw.py'>) not available
[w] Cannot bind framebuffer
[w] Cannot read RED channel size from the framebuffer
[w] Cannot read GREEN channel size from the framebuffer
[w] Cannot read BLUE channel size from the framebuffer
[w] Cannot read ALPHA channel size from the framebuffer
[w] Cannot read DEPTH size from the framebuffer
[w] Cannot read STENCIL size from the framebuffer
[w] Cannot read sRGB value from the framebuffer
Traceback (most recent call last):
  File "C:\Users\jeff5\Desktop\Python\OpenGL_Exercises\Example1.py", line 17, in <module>
    window = app.Window()
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\app\__init__.py", line 186, in __new__
    config = configuration.gl_get_configuration()
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\glumpy\app\configuration.py", line 354, in gl_get_configuration
    configuration._samples       = gl.glGetInteger(gl.GL_SAMPLES)
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\OpenGL\latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\OpenGL\wrapper.py", line 674, in wrapperCall
    raise err
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\OpenGL\wrapper.py", line 667, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "C:\Users\jeff5\AppData\Roaming\Python\Python36\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glGetIntegerv,
	pyArgs = (
		GL_SAMPLES,
		<object object at 0x000002069EBEC490>,
	),
	cArgs = (GL_SAMPLES, array([0], dtype=int32)),
	cArguments = (GL_SAMPLES, array([0], dtype=int32))
)
>>> 

Code in glumpy\app\__init__.py around where the module is called starting line 112.

   # BUG: For some reason, the import module changes the working directory
    #      We save it beforehand and restore it just after
    workdir = os.getcwd()
    name = "glumpy.app.window.backends.backend_" + backend
    importlib.import_module(name)
    backend = sys.modules[name]
    os.chdir(workdir)

    # Check availability
    if backend.available():
        __backend__ = backend
        return backend
    else:
        log.warning("Backend (%s) not available" % backend)
        return None

**Comment by rougier** [comment]
Sorry for the latex answer. I think your version of OpenGL might be too old and do not know the `GL_SAMPLES` enumerant. Do you know what is your version ?

**Comment by sam598** [comment]
Is there a minimum supported version of OpenGL for Glumpy?

I'm having a similar issue on a Raspberry Pi. The pip version of Glumpy works great on the device, but the latest version of Glumpy from GitHub reports several missing "backends" when trying to create a window.

`glxinfo | grep "OpenGL version"` says the version of OpenGL is `OpenGL version string: 3.0 Mesa 18.0.5`

Here is the full error:

```
[w] Backend (<module 'glumpy.app.window.backends.backend_glfw' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_glfw.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_pyglet' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_pyglet.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_sdl' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_sdl.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_sdl2' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_sdl2.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_osxglut' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_osxglut.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_freeglut' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_freeglut.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_qt5' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_qt5.py'>) not available
[w] Backend (<module 'glumpy.app.window.backends.backend_pyside' from '/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/window/backends/backend_pyside.py'>) not available
[x] No suitable backend found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/glumpy-1.0.6-py3.5-linux-armv7l.egg/glumpy/app/__init__.py", line 157, in __new__
    raise NotImplementedError
NotImplementedError
```

**Comment by rougier** [comment]
Backends are the toolkit used to open a window and handle mouse events. As long as you have one working, it is fine (unless you need a specific one). GLFW is the preferred backend because it is small and give access to many features of OpenGL. This means you have to install it on your system (both c library and headers).

**Comment by MY2918** [comment]
In case this is still of interest, 
install sudo apt-get install libglfw3
