### ISSUE TITLE
'np' is not defined

### ISSUE THREAD

**Issue by AndrewYinLi** [glumpy/glumpy#158]
When I attempt to define a new ```Translate(...)```, I get the following:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\ProgramData\Anaconda3\envs\p3\lib\site-packages\glumpy\app\window\backends\backend_glfw.py", line 269, in on_keyboard
    self.dispatch_event('on_key_press', symbol, modifiers)
  File "C:\ProgramData\Anaconda3\envs\p3\lib\site-packages\glumpy\app\window\event.py", line 384, in dispatch_event
    if handler(*args):
  File "lasclasseyeglass.py", line 123, in on_key_press
    ptsRender["transform"] = Translate("position", translate=t)
  File "C:\ProgramData\Anaconda3\envs\p3\lib\site-packages\glumpy\transforms\translate.py", line 46, in __init__
    self.translate = Transform._get_kwarg("translate", kwargs) or (0,0,0)
  File "C:\ProgramData\Anaconda3\envs\p3\lib\site-packages\glumpy\transforms\translate.py", line 60, in translate
    self._translate = np.asarray(value,dtype=np.float32)
NameError: name 'np' is not defined
```
My suspicion is some library imported by translate.py is missing ```import numpy as np```.

**Comment by rougier** [comment]
You're probably right and the import is most likely missing from `translate.py`.  Did you try to add it in this file to check if it fixes the issue?

**Comment by AndrewYinLi** [comment]
Yes, it fixes the issue. I'm wondering if ```numpy``` is used by other classes than ```translate.py```? I'll give it a look and create a pull request sometime in the next day or so.

**Comment by rougier** [comment]
Numpy is used pretty much everywhere in glumpy.

**Comment by AndrewYinLi** [comment]
Of course, I meant in glumpy/glumpy/transforms/.
