### ISSUE TITLE
Using glumpy with GLFW3 installed in home directory

### ISSUE THREAD

**Issue by kushal-sharma** [glumpy/glumpy#161]
I am trying to run the following test code - 
```
from glumpy import app, gloo, gl

vertex = """
    attribute vec2 position;
    void main(){ gl_Position = vec4(position, 0.0, 1.0); } """

fragment = """
    void main() { gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); } """

# Create a window with a valid GL context
window = app.Window()

# Build the program and corresponding buffers (with 4 vertices)
quad = gloo.Program(vertex, fragment, count=4)

# Upload data into GPU
quad['position'] = (-1,+1), (+1,+1), (-1,-1), (+1,-1)

# Tell glumpy what needs to be done at each redraw
@window.event
def on_draw(dt):
    window.clear()
    quad.draw(gl.GL_TRIANGLE_STRIP)

# Run the app
app.run()
```

I have GLFW-3.2.1 installed in the home directory via -
```
mkdir build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/lib
make & make install
```
This puts a `libglfw3.a` inside `$HOWE/lib/lib`. In branch Tag - 1.0.3, on line 47 of `glumpy/ext/glfw.py` there is check to find glfw using environment variable 'GLFW_LIBRARY`. I set this using `export GLFW_LIBRARY=$HOME/lib/lib/libglfw3.a` . But this gives me the following error - 
```
Traceback (most recent call last):
  File "vis.py", line 11, in <module>
    window = app.Window()
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/site-packages/glumpy/app/__init__.py", line 150, in __new__
    backend = use(name)
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/site-packages/glumpy/app/__init__.py", line 116, in use
    importlib.import_module(name)
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/site-packages/glumpy/app/window/backends/backend_glfw.py", line 82, in <module>
    from glumpy.ext import glfw
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/site-packages/glumpy/ext/glfw.py", line 63, in <module>
    _glfw = ctypes.CDLL(_glfw_file)
  File "/home/sharma/miniconda3/envs/laser_int/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sharma/lib/lib/libglfw3.a: invalid ELF header
```
I think this is because on line 60 of glumpy/ext/glfw.py, ctypes.cdll function is beign used 
```
_glfw = ctypes.CDLL(_glfw_file)
```
and .a is a static library. Is the some other location expected in the environment variable ?

**Comment by kushal-sharma** [comment]
Compiling GLFW with BUILD_SHARED_LIBS option as here - http://www.glfw.org/docs/latest/compile.html does the trick. This creates a libglfw3.so along with libglfw3.a

**Comment by rougier** [comment]
Thanks for reporting the solution (added a tip label)
