### ISSUE TITLE
Misleading shader compilation error

### ISSUE THREAD

**Issue by vznncv** [glumpy/glumpy#162]
The `glumpy` shows only first  shader compilation error/warning. So it can cause wrong error message.

For example, the following program:
```
from glumpy import app, gloo, gl


def main():
    window = app.Window()

    # vertex shader
    vertex = r'''
        uniform float time;
        attribute vec2 position;
        def main() { // the string with actual error
            vec2 xy = vec2(sin(time * 0.2));
            gl_Position = vec4(position * (0.25 + 0.75 * xy * xy), 0.0, 1.0);
        }
    '''
    # fragment shader
    fragment = '''
        uniform vec4 color;
        void main() {
            gl_FragColor = color;
        }
    '''
    # square object
    quad = gloo.Program(vertex, fragment, count=4)

    # set square coordinates and color
    quad['position'] = [(-0.5, -0.5),
                        (-0.5, +0.5),
                        (+0.5, -0.5),
                        (+0.5, +0.5)]
    quad['color'] = 1, 0, 0, 1  # red color

    quad['time'] = 0

    @window.event
    def on_draw(dt):
        window.clear()
        # draw square
        quad["time"] += dt
        quad.draw(gl.GL_TRIANGLE_STRIP)

    app.run()


if __name__ == '__main__':
    main()
```

shows the error:
```
[i] Using GLFW (GL 3.0)
[i] Running at 60 frames/second
Error in Vertex shader 2 (<string>)
 -> preprocessor warning: Macro names containing "__" are reserved for use by the implementation.

 000 #define _GLUMPY__VERTEX_SHADER__
 001 // --- Snippets code : start --- //
 002 // --- Snippets code : end --- //
 ...

Traceback (most recent call last):
  File "/media/D/CodeExamples/Python/glumpy_examples/example_3_square_movement.py", line 46, in <module>
    main()
  File "/media/D/CodeExamples/Python/glumpy_examples/example_3_square_movement.py", line 42, in main
    app.run()
  File "/media/D/CodeExamples/Python/glumpy/glumpy/app/__init__.py", line 317, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/media/D/CodeExamples/Python/glumpy/glumpy/app/__init__.py", line 277, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/media/D/CodeExamples/Python/glumpy/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/media/D/CodeExamples/Python/glumpy/glumpy/app/window/window.py", line 221, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/media/D/CodeExamples/Python/glumpy/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "/media/D/CodeExamples/Python/glumpy_examples/example_3_square_movement.py", line 40, in on_draw
    quad.draw(gl.GL_TRIANGLE_STRIP)
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/program.py", line 603, in draw
    self.activate()
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/globject.py", line 86, in activate
    self._create()
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/program.py", line 181, in _create
    self._build_shaders(self._handle)
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/program.py", line 229, in _build_shaders
    shader.activate()
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/globject.py", line 96, in activate
    self._update()
  File "/media/D/CodeExamples/Python/glumpy/glumpy/gloo/shader.py", line 244, in _update
    raise RuntimeError("Shader compilation error")
RuntimeError: Shader compilation error

Process finished with exit code 1
```

whereas it should show:
```
def main() { // the string with actual error
```

**Comment by vznncv** [comment]
The fix has been merged into master branch.
