### ISSUE TITLE
Raise "Not a valid Win32 Application"

### ISSUE THREAD

**Issue by ShannonZ** [glumpy/glumpy#166]
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from glumpy import app
>>> window = app.Window()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda3\lib\site-packages\glumpy\app\__init__.py", line 150, in __new__
    backend = use(name)
  File "c:\Anaconda3\lib\site-packages\glumpy\app\__init__.py", line 116, in use
    importlib.import_module(name)
  File "c:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\Anaconda3\lib\site-packages\glumpy\app\window\backends\backend_glfw.py", line 82, in <module>
    from glumpy.ext import glfw
  File "c:\Anaconda3\lib\site-packages\glumpy\ext\glfw.py", line 63, in <module>
    _glfw = ctypes.CDLL(_glfw_file)
  File "c:\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 Not a valid Win32 Application

**Comment by rougier** [comment]
Does it work outside anaconda?

**Comment by ShannonZ** [comment]
fixed
It was caused by GLFW. I build a new GLFW.dll on my computer and now works fine
