### ISSUE TITLE
window.event doesn't work in python 3.6 if you use a string since unicode is not a keyword anymore

### ISSUE THREAD

**Issue by CodeDoes** [glumpy/glumpy#176]

**Comment by rougier** [comment]
Could you give some details or a minimal example showing the problem?

**Comment by CodeDoes** [comment]
on python 3.6
```python3
@window.event("on_idle")
def foo(*a):
    pass
```
```
[i] HiDPI detected, fixing window size
[i] Using GLFW (GL 2.1)
Traceback (most recent call last):
  File "glumpy_demo.py", line 204, in <module>
    window.event("on_draw",on_draw)
  File "/home/kitkat/.local/lib/python3.6/site-packages/glumpy/app/window/event.py", line 481, in event
    elif type(args[0]) in (str, unicode):   # @window.event('on_resize')
NameError: name 'unicode' is not defined

```

**Comment by rougier** [comment]
Do you know if testing only for "str" would be sufficient ?

**Comment by rougier** [comment]
Ok. Can you make a PR?

**Comment by CodeDoes** [comment]
@rougier done :smile:
