### ISSUE TITLE
Python36 Windows10  RuntimeError: Freetype library not found

### ISSUE THREAD

**Issue by nickums** [glumpy/glumpy#182]
A beautiful package, beautiful documentation,    beaurtiful examples but I dont have a freetype library,  so examples  fail.   
 in my shell print(ctypes.util.find_library("freetype")) gives None.Traceback (most recent call last):

  File "C:/Python/Python36/Dhruve and me/Glumpy/gloo-framebuffer.py", line 9, in <module>
    from glumpy import app, gl, gloo
  File "C:\Python\Python36\lib\site-packages\glumpy\__init__.py", line 7, in <module>
    from . import app
  File "C:\Python\Python36\lib\site-packages\glumpy\app\__init__.py", line 16, in <module>
    from glumpy.ext.inputhook import inputhook_manager, stdin_ready
  File "C:\Python\Python36\lib\site-packages\glumpy\ext\__init__.py", line 6, in <module>
    from . import freetype
  File "C:\Python\Python36\lib\site-packages\glumpy\ext\freetype\__init__.py", line 49, in <module>
    raise RuntimeError('Freetype library not found')
RuntimeError: Freetype library not found

**Comment by rougier** [comment]
You can try to install the freetype-py bindings that will install freetype on your system. Maybe I should get rid of the internal copy of freetype-py and use the "official" one.

**Comment by nickums** [comment]
Installing freetype-py and updating ext directory fixed that problem.
I then found a similar problem with glfw, which I fixed the same way.
Thanks for the hint!
