### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'type'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [glumpy/glumpy#197]
Can't install due to:

```
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import numpy
  File "/home/username/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/username/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 57, in <module>
    from . import numerictypes as nt
  File "/home/username/.local/lib/python2.7/site-packages/numpy/core/numerictypes.py", line 111, in <module>
    from ._type_aliases import (
  File "/home/username/.local/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in <module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/home/username/.local/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in <setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'

```

**Comment by rougier** [comment]
Did you tried with Python 3 (preferred)?
