### ISSUE TITLE
Triangulate - assertion error

### ISSUE THREAD

**Issue by prithivi-iviz** [glumpy/glumpy#214]
Examples such as collection-triangles.py, tiger.py fails to run due to the below error,

 line 66, in triangulate
    tri, _ = triang(tri, opts)
  File "triangle/core.pyx", line 247, in triangle.core.triang
  File "triangle/core.pyx", line 219, in triangle.core.fin
  File "triangle/core.pyx", line 74, in triangle.core.ii._set
  File "triangle/core.pyx", line 115, in triangle.core._wrap.check
AssertionError

**Comment by rougier** [comment]
I just updated the triangle library and I now have the error. I guess something has changed in the library and I need to investigate.

**Comment by rougier** [comment]
I've opened an [issue](https://github.com/drufat/triangle/issues/34) on the triangle repository.

**Comment by rougier** [comment]
And @drufat just fixed the errror in glumpy.

**Comment by GitHub-Mike** [comment]
I have the same issue with tiger.py as @prithivi-iviz 

> [i] Requesting "tiger.svg" from remote server
[i] Fetching data (110724 bytes) to "<path>\glumpy\data\tiger.svg"
[w] Unhandled SVG tag (metadata)
[w] Unhandled SVG tag (defs)
[i] Using GLFW (GL 4.3)
Traceback (most recent call last):
  File "<path>/glumpy_examples/tiger.py", line 59, in <module>
    polygons.append(vertices, color=path.style.fill.rgba)
  File "<path>\glumpy\graphics\collections\raw_polygon_collection.py", line 83, in append
    vertices, indices = triangulate(points)
  File "<path>\glumpy\graphics\collections\raw_polygon_collection.py", line 21, in triangulate
    'segments': segments}, "p")
  File "<path>\triangle\tri.py", line 66, in triangulate
    tri, _ = triang(tri, opts)
  File "triangle/core.pyx", line 247, in triangle.core.triang
  File "triangle/core.pyx", line 219, in triangle.core.fin
  File "triangle/core.pyx", line 74, in triangle.core.ii._set
  File "triangle/core.pyx", line 115, in triangle.core._wrap.check
AssertionError

I use WIN10 PRO, Python 3.7, glumpy 1.1.0 and triangle 2019.0115.3

Can you reopen the issue or should I create a new issue?

**Comment by rougier** [comment]
Do you use GitHub version (for glumpy) ?

**Comment by GitHub-Mike** [comment]
I use this version: https://github.com/glumpy/glumpy/blob/master/examples/tiger.py

I thought only the package was changed and not the examples!?

**Comment by rougier** [comment]
Glumpy has been update because there were a problem with the triangle use (see #216), if you're using an older version, you might have problem.

**Comment by GitHub-Mike** [comment]
I can't understand that. Glumpy 1.1.0 is the latest version, isn't it? Should I download the master repository from here or is there a more recent version of the tiger.py example?

**Comment by GitHub-Mike** [comment]
OK, I see the problem now. The patch is not yet installed in Glumpy version 1.1.0.
I made the change manually now and it works!

At this point I would like to express my respect for the many projects you have published here at github and on the web. This is a great help and inspiration for every Python user.

Thanks for that!!!
