### ISSUE TITLE
Crash on install.

### ISSUE THREAD

**Issue by brorfred** [glumpy/glumpy#22]
Installing glumpy on a Mac with Yosemite with sudo pip install --update glumpy. Crashes as follows:

```
...
copying glumpy/library/collections/raw-point.frag -> build/lib.macosx-10.10-x86_64-2.7/glumpy/library/collections

copying glumpy/library/collections/raw-segment.frag -> build/lib.macosx-10.10-x86_64-2.7/glumpy/library/collections

copying glumpy/library/collections/raw-triangle.frag -> build/lib.macosx-10.10-x86_64-2.7/glumpy/library/collections

copying glumpy/library/collections/sdf-glyph.frag -> build/lib.macosx-10.10-x86_64-2.7/glumpy/library/collections

running build_ext

cythoning glumpy/ext/sdf/_sdf.pyx to glumpy/ext/sdf/_sdf.c

error: [Errno 2] No such file or directory: '/private/tmp/pip_build_root/glumpy/glumpy/ext/sdf/_sdf.pyx'

----------------------------------------
  Rolling back uninstall of glumpy
Cleaning up...
Command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/glumpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Za3Kcz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/glumpy
Storing debug log for failure in /Users/bror/.pip/pip.log
```

Tried on two different machines which both have macport installed

**Comment by brorfred** [comment]
End of the log file:
```
python2.7/site-packages/glumpy/window/window.pyc
Cleaning up...
  Removing temporary dir /private/tmp/pip_build_root...
Command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/glumpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Za3Kcz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/glumpy
Exception information:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/glumpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Za3Kcz-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/glumpy
```

**Comment by rougier** [comment]
Sorry about that, wrong setup file. I just corrected it and uploaded the fixed version to pypi.
