### ISSUE TITLE
On close with pyglet backend error 

### ISSUE THREAD

**Issue by robintwhite** [glumpy/glumpy#250]
I am getting an error of 'NoneType' object has no attribute flip when using pyglet backend. This occurs when the window closes in the swap function call. Is it perhaps calling this function after the window already closes so there is nothing to perform the flip() method?
I am running on windows 10, python 3.7.6, pyglet 1.5.5, glumpy 1.1.0

**Comment by rougier** [comment]
Can you try with a minimal example from the examples directory (app-simple.py) using the `--debug` flag and post the Traceback ?

**Comment by robintwhite** [comment]
This is what I ran:
from glumpy import app
app.use("pyglet")

window = app.Window()

@window.event
def on_draw(dt):
    window.clear()

app.run()


This is what I received:
(Pygmy) D:\Github\Pygmy\Shader_Test>python glumpy_pyglet_test.py --debug
OpenGL_accelerate seems to be installed, but unable to import error checking entry point!
Unable to load ArrayDatatype accelerator from OpenGL_accelerate
Unable to load converters accelerators (wrapper, arraydatatype) from OpenGL_accelerate
Unable to load arrayhelpers accelerator from OpenGL_accelerate
OpenGL_accelerate seems to be installed, but unable to import expected wrapper entry points!
Unable to load VBO accelerator from OpenGL_accelerate
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
[i] Using Pyglet (GL 4.6)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "glumpy_pyglet_test.py", line 14, in <module>
    app.run()
  File "C:\Users\Robin\anaconda3\envs\Pygmy\lib\site-packages\glumpy\app\__init__.py", line 362, in run
    run(duration, framecount)
  File "C:\Users\Robin\anaconda3\envs\Pygmy\lib\site-packages\glumpy\app\__init__.py", line 344, in run
    count = __backend__.process(dt)
  File "C:\Users\Robin\anaconda3\envs\Pygmy\lib\site-packages\glumpy\app\window\backends\backend_pyglet.py", line
302, in process
    window.swap()
  File "C:\Users\Robin\anaconda3\envs\Pygmy\lib\site-packages\glumpy\app\window\backends\backend_pyglet.py", line
273, in swap
    self._native_window.flip()
  File "C:\Users\Robin\anaconda3\envs\Pygmy\lib\site-packages\pyglet\window\win32\__init__.py", line 352, in flip
    self.context.flip()
AttributeError: 'NoneType' object has no attribute 'flip'

FYI I having opengl-accelerate v 3.1.5 installed - I am not really sure of those errors

**Comment by rougier** [comment]
I think your former analysis is right and we have the same problem on Qt. Context is destroyed when the window is closed and there is a pending flip that is issued on a None context. Maybe the flip needs a try/catch.

**Comment by Gls-Facom** [comment]
Any progress on solving this issue?

**Comment by rougier** [comment]
Just forgot about this issue. You mean it's still present?

**Comment by Gls-Facom** [comment]
Yes. I'm running Windows 10, python 3.10.4, glumpy 1.2.0, pyglet 1.5.26

**Comment by rougier** [comment]
Do you get the same traceback?

**Comment by Gls-Facom** [comment]
Yes

**Comment by rougier** [comment]
I just made a test using latest python/glumpy(git) and pyglet on OSX and I do not have the problem. Do you know if pyglet is working properly on your machine?
