### ISSUE TITLE
NameError: name 'raw_input' is not defined in glumpy.app.window.backends.backend_glfw

### ISSUE THREAD

**Issue by qiujiangkun** [glumpy/glumpy#267]
glumpy.app.window.backends.backend_glfw
```log
Traceback (most recent call last):
  File "<string>", line 23, in <module>
NameError: name 'raw_input' is not defined
```

**Comment by qiujiangkun** [comment]
I figured out that my glfw failed because my glfw was in the wrong version. But since I'm using python 3 there should not be raw_input() anyway

**Comment by rougier** [comment]
Sorry. for the delay. Can you give me some context for this error? When does it happen?

**Comment by qiujiangkun** [comment]
When I was debugging with PyCharm with capturing all exceptions, I always got this message. I'm trying to locate the code and make a pull request.
```log
Connected to pydev debugger (build 202.7660.27)
Traceback (most recent call last):
  File "<string>", line 23, in <module>
NameError: name 'raw_input' is not defined
python-BaseException
```

**Comment by qiujiangkun** [comment]
Got it. It's in `glumpy/ext/glfw.py`
```python. 
def _glfw_get_version(filename):
    """
    Queries and returns the library version tuple or None by using a
    subprocess.
    """
    version_checker_source = '''
        import sys
        import ctypes
        def get_version(library_handle):
            """
            Queries and returns the library version tuple or None.
            """
            major_value = ctypes.c_int(0)
            major = ctypes.pointer(major_value)
            minor_value = ctypes.c_int(0)
            minor = ctypes.pointer(minor_value)
            rev_value = ctypes.c_int(0)
            rev = ctypes.pointer(rev_value)
            if hasattr(library_handle, 'glfwGetVersion'):
                library_handle.glfwGetVersion(major, minor, rev)
                version = (major_value.value,
                           minor_value.value,
                           rev_value.value)
                return version
            else:
                return None
        try:
            input_func = raw_input
        except NameError:
            input_func = input
        filename = input_func().strip()
        try:
            library_handle = ctypes.CDLL(filename)
        except OSError:
            pass
        else:
            version = get_version(library_handle)
            print(version)
    '''

    args = [sys.executable, '-c', textwrap.dedent(version_checker_source)]
    process = subprocess.Popen(args, universal_newlines=True,
                               stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    out = process.communicate(filename)[0]
    out = out.strip()
    if out:
        return eval(out)
    else:
        return None

```

**Comment by rougier** [comment]
Thanks. It's weird because it is enclosed  by try/catch. Can you try without the `NameError` specification just to check if we can catch the exception whatever it is ?

**Comment by qiujiangkun** [comment]
The `NameError` is actually caught. It was also identified by Python debugger. It's not a bug actually.
