### ISSUE TITLE
./run-simple.py error

### ISSUE THREAD

**Issue by xuexiaoxiaohu** [glumpy/glumpy#270]
I follow the installation and run this python file but an error exists as follows
(pt1) li@li:~/download/glumpy/examples$ python ./app-simple.py
Traceback (most recent call last):
  File "./app-simple.py", line 7, in <module>
    window = app.Window()
  File "/home/li/anaconda3/envs/pt1/lib/python3.7/site-packages/glumpy/app/__init__.py", line 157, in __new__
    raise NotImplementedError
NotImplementedError
Thanks a lot if you reply

**Comment by rougier** [comment]
You need to have a backend installed, one of Qt, GLFW, pyglet or pygame.

**Comment by rougier** [comment]
For glfw, you also need to have th C library installed (glfw are only the bindings I think). Do you know if it is the case?
