### ISSUE TITLE
matplotlib 1 and 2 examples don't work

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#29]
```
[i] Using GLFW (GL 3.0)
[i] Enforcing viewport aspect ratio (1)
[i] Enforcing viewport aspect ratio (1)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "examples/matplotlib-2.py", line 42, in <module>
    figure.show()
  File "/data/git/glumpy/glumpy/api/matplotlib/figure.py", line 27, in show
    app.run()
  File "/data/git/glumpy/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/data/git/glumpy/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 375, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/data/git/glumpy/glumpy/app/window/window.py", line 193, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 365, in dispatch_event
    if handler(*args):
  File "/data/git/glumpy/glumpy/app/viewport.py", line 425, in on_draw
    child.dispatch_event("on_draw", dt)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 375, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/data/git/glumpy/glumpy/api/matplotlib/axes.py", line 102, in on_draw
    drawable.draw()
  File "/data/git/glumpy/glumpy/graphics/collections/collection.py", line 261, in draw
    draw(program, mode)
NameError: global name 'draw' is not defined
```

**Comment by rougier** [comment]
Thanks, this one has been fixed.

**Comment by rossant** [comment]
still not fixed for me...

**Comment by rougier** [comment]
Forgot to push, can you retry ?

**Comment by rossant** [comment]
works, thanks!
