### ISSUE TITLE
Glumpy not matching correctly shape of VBO

### ISSUE THREAD

**Issue by VictorGoubet** [glumpy/glumpy#319]
I am creating a verify basic simulation of bubbles using glumpy and I'm facing issue defining a uniform array of vec3. It seems that glumpy failed to evaluate correctly the shape of the object.

Here is the complete fragment shader:

```glsl
#version 330 core

const int num_circles = 2;
uniform vec3 circlePt[num_circles];
uniform vec2 u_resolution;
out vec4 fragColor;

float circle(vec2 px, vec3 cp) {
    vec2 dist = px - cp.xy;
    float r = cp.z;
    return 1 - smoothstep(r - (r * 0.01), r + (r * 0.01), dot(dist, dist) * 4.0);
}

void main() {
    vec2 px = gl_FragCoord.xy / u_resolution.xy;
    float c = 1;
    for(int i = 0; i < num_circles; i++) {
        c = min(c, circle(px, circlePt[i]));
    }
    fragColor = vec4(c, c, c, 1);
}
```

And here is the python part (check run method)

```python
class Simulation:
    """Simulation of bubbles"""

    def __init__(self) -> None:
        """Initialize the simulation"""
        self.width = 1000
        self.height = 1000
        self.version = "330"
        self.init_windows()

    def init_windows(self) -> None:
        """Initialize the windows"""
        app.use(
            backend="glfw",
            api="GL",
            major=int(self.version[0]),
            minor=int(self.version[1]),
            profile="core",
        )
        self.loading_shaders()
        self.window = app.Window()

    def loading_shaders(self) -> None:
        """Load shaders"""
        with open("./shaders/vertex.glsl", "r") as f:
            self.vertex = f.read()
        with open("./shaders/fragment.glsl", "r") as f:
            self.fragment = f.read()

    def run(self) -> None:
        """Run the simulation"""
        quad = gloo.Program(
            self.vertex,
            self.fragment,
            count=4,
            version=self.version,
        )

        # Define buffers
        dtype = [
            ("vertices", np.float32, 2),
            ("u_resolution", np.float32, 2),
            ("circlePt", np.float32, 3),
        ]
        quad_arrays = np.zeros(4, dtype).view(gloo.VertexArray)
        quad_arrays["vertices"] = [(-1, -1), (-1, 1), (1, -1), (1, 1)]
        quad_arrays["u_resolution"] = (self.width, self.height)
        quad["circlePt"] = [(0.25, 0.25, 0.1), (0.0, 0.25, 0.05)]
        quad.bind(quad_arrays)

        @self.window.event
        def on_draw(dt):
            self.window.clear()
            quad.draw(gl.GL_TRIANGLE_STRIP)

        app.run()
```

However it failed with the following error

```bash
$ python3 main.py 
[i] Using GLFW (GL 3.3)
Traceback (most recent call last):
  File "main.py", line 112, in <module>
    sim.run()
  File "main.py", line 52, in run
    quad["circlePt"] = [(0.25, 0.25, 0.1), (0.0, 0.25, 0.05)]
  File "venv/lib/python3.10/site-packages/glumpy/gloo/program.py", line 353, in __setitem__
    self._uniforms[name].set_data(data)
  File "venv/lib/python3.10/site-packages/glumpy/gloo/variable.py", line 261, in set_data
    self._data[...] = np.array(data,copy=False).ravel()
ValueError: could not broadcast input array from shape (6,) into shape (3,)
```
I don't know if I'm not using correctly the library of if glumpy fail to match the correct shape

**Comment by rougier** [comment]
You closed the issue beause it is solved ?

**Comment by VictorGoubet** [comment]
It's not an issue related to glumpy but just the way open gl is designed. It seems that we can't declare multiple dimensions uniform variables. I used texture instead, I could also use uniform 1D array and do the indexing my self. If you have better suggestions keep me informed! :)
