### ISSUE TITLE
snippet-grids example does not work

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#33]
Intel GPU:
```
[i] Using GLFW (GL 3.0)
[i] Running at 60 frames/second
error: fragment shader varying v_index_4 not written by vertex shader
.error: fragment shader varying v_x_4 not written by vertex shader
.
Traceback (most recent call last):
  File "examples/snippet-grids.py", line 106, in <module>
    app.run()
  File "/data/git/glumpy/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/data/git/glumpy/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 375, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/data/git/glumpy/glumpy/app/window/window.py", line 193, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 365, in dispatch_event
    if handler(*args):
  File "examples/snippet-grids.py", line 82, in on_draw
    program.draw(gl.GL_LINE_STRIP)
  File "/data/git/glumpy/glumpy/gloo/program.py", line 499, in draw
    self.activate()
  File "/data/git/glumpy/glumpy/gloo/globject.py", line 87, in activate
    self._create()
  File "/data/git/glumpy/glumpy/gloo/program.py", line 155, in _create
    raise ValueError('Linking error')
ValueError: Linking error
```

NVIDIA GPU:
![image](https://cloud.githubusercontent.com/assets/1942359/6751038/4f89731c-cf00-11e4-8c27-bf0ef8e7ac53.png)

and scrolling => 
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/data/git/glumpy/glumpy/app/window/backends/backend_glfw.py", line 288, in on_scroll
    self.dispatch_event('on_mouse_scroll', x, y, xoffset, yoffset)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 365, in dispatch_event
    if handler(*args):
  File "examples/snippet-grids.py", line 90, in on_mouse_scroll
    program['xscale'] *= np.exp(2.5*dx)
  File "/data/git/glumpy/glumpy/gloo/program.py", line 333, in __getitem__
    raise IndexError("Unknown item (no corresponding hook, uniform or attribute)")
IndexError: Unknown item (no corresponding hook, uniform or attribute)
```

**Comment by rougier** [comment]
Yes, this is broken. You might prefer to test `collection-update.py`

**Comment by rossant** [comment]
> You might prefer to test collection-update.py

Nice. However the mouse wheel doesn't do anything.

**Comment by rougier** [comment]
Weird, this should scale the signal when you're over it.
Does the signal under the mouse become white ?
If you write a `print "toto"`  within the `on_mouse_scroll` event, does it get printed ?

**Comment by rossant** [comment]
> Weird, this should scale the signal when you're over it.

it doesn't

> Does the signal under the mouse become white ?

yes

> If you write a print "toto" within the on_mouse_scroll event, does it get printed ?

yes

**Comment by rougier** [comment]
So do all signals have different scales at start ?
Can you print `lines["xscale"][index]`in the on_scroll_event and check if it get changed ?

**Comment by rossant** [comment]
Yes it does get changed, but the scale doesn't appear to change on screen.
Weird...

**Comment by rougier** [comment]
Can you add (after if selected > 0.0)
```
v_color=vec4(1,xscale/100.0,0,1);
```

The signal should change color (red to yellow) with mouse scroll.

**Comment by rossant** [comment]
no change...

**Comment by rougier** [comment]
Can you try this:
```
    print lines._vertices_buffer._pending_data
    lines["xscale"][index] *= np.exp(2.5*dx)
    lines["xscale"][index] = min(max(1.0, lines["xscale"][index]),100)
    print lines._vertices_buffer._pending_data
```

**Comment by rossant** [comment]
```
None
(0, 6412800)
```

**Comment by rougier** [comment]
You get only two lines ?
First mean buffer do not need upload, second tells the area to be uploaded. Each time you scroll, you should get these two lines (or twice the last if mouse scroll is too fast), indicating the buffer has been uploaded.

**Comment by rossant** [comment]
Here is a more complete output with

```python
@window.event
def on_mouse_scroll(x, y, dx, dy):
    index = get_index(x,y)
    dx = -np.sign(dy) * .05
    # lines["xscale"][index] *= np.exp(2.5*dx)
    # lines["xscale"][index] = min(max(1.0, lines["xscale"][index]),100)

    print '--------'
    print lines._vertices_buffer._pending_data
    lines["xscale"][index] *= np.exp(2.5*dx)
    lines["xscale"][index] = min(max(1.0, lines["xscale"][index]),100)
    print lines._vertices_buffer._pending_data
    print
```

```
(py27)cyrille@gigabyte:~/git/glumpy$ python examples/collection-update.py 
[i] Using GLFW (GL 3.0)
[i] Running at 60 frames/second
--------
(0, 6412800)
(0, 6412800)

--------
None
(0, 6412800)

--------
None
(0, 6412800)

--------
None
(0, 6412800)

--------
(0, 6412800)
(0, 6412800)

--------
None
(0, 6412800)

--------
None
(0, 6412800)

--------
(0, 6412800)
(0, 6412800)

--------
None
(0, 6412800)

--------
None
(0, 6412800)

--------
(0, 6412800)
(0, 6412800)
```

**Comment by rougier** [comment]
Another idea to test (should scale all signals at once)
```
@window.event
def on_mouse_scroll(x, y, dx, dy):
    index = get_index(x,y)
    dx = -np.sign(dy) * .05
    lines["xscale"] *= np.exp(2.5*dx)
    lines["xscale"] = min(max(1.0, lines["xscale"]),100)
```

**Comment by rossant** [comment]
```
[i] Using GLFW (GL 3.0)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/data/git/glumpy/glumpy/app/window/backends/backend_glfw.py", line 288, in on_scroll
    self.dispatch_event('on_mouse_scroll', x, y, xoffset, yoffset)
  File "/data/git/glumpy/glumpy/app/window/event.py", line 365, in dispatch_event
    if handler(*args):
  File "examples/collection-update.py", line 127, in on_mouse_scroll
    lines["xscale"] = min(max(1.0, lines["xscale"]),100)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

![image](https://cloud.githubusercontent.com/assets/1942359/6769413/832d6430-d09a-11e4-9021-664fb2b4fa43.png)

**Comment by rougier** [comment]
Dams. Can you comment the line (or replae with  minimum/maximum instead of min/max) ?

**Comment by rossant** [comment]
Commenting the line = no more error messages, but the screenshot is the same.

**Comment by rougier** [comment]
I think I have found. your texture is most probably clamped between 0 and 1 by the GPU. Since xscale is between 0 and 100, it does not work. Can you try to add xscale*100 in the shader where necessary, and use:

```
@window.event
def on_mouse_scroll(x, y, dx, dy):
    index = get_index(x,y)
    dx = -np.sign(dy) * .005
    lines["xscale"][index] *= np.exp(2.5*dx)
    lines["xscale"][index] = min(max(0.01, lines["xscale"][index]),1.0)
```

**Comment by rossant** [comment]
Yep that was the problem!
