### ISSUE TITLE
Examples fail to run, aborting with a raised "Unknown GLSL error format"

### ISSUE THREAD

**Issue by matthew-egbert** [glumpy/glumpy#46]
I tried a few examples, including https://github.com/glumpy/glumpy/blob/master/examples/gloo-antialias.py and they fail with the following error. I have just noticed that glxinfo is showing that direct rendering is not working. I am not sure if that is causing the problem.

python main.py
[i] Using GLFW (GL 4.4)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/window/event.py", line 375, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/window/event.py", line 365, in dispatch_event
    if handler(*args):
  File "main.py", line 18, in on_draw
    program.draw(gl.GL_POINTS)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/program.py", line 499, in draw
    self.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/globject.py", line 87, in activate
    self._create()
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/program.py", line 147, in _create
    self._build_shaders(self._handle)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/program.py", line 195, in _build_shaders
    shader.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/shader.py", line 205, in _update
    lineno, mesg = self._parse_error(error)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/gloo/shader.py", line 242, in _parse_error
    raise ValueError('Unknown GLSL error format')
ValueError: Unknown GLSL error format

Compilation exited abnormally with code 1 at Mon Aug 31 15:14:35

**Comment by rougier** [comment]
What is your OS ? if linux or osx, you can try `glxinfo` to check if rendering is direct or not.
And you're right, no direct rendering may make things not work.

Also, you can try `vispy` at http://vispy.org which is the sister project of glumpy but is far better tested

**Comment by rougier** [comment]
Sorry, just saw you were saying glxinfo reports no direct rendering. Do you know why it is not working ? Do you known what is your GPU ? What about running glxinfo as root ?

**Comment by matthew-egbert** [comment]
I just rebooted and direct rendering now works and now so do the examples. Bizarre.

**Comment by rougier** [comment]
Yep, strange. Can I close the issue then ?

**Comment by matthew-egbert** [comment]
Sure, although it would be nice for the error message to spit out the glsl
error that it couldn't parse! Thanks for your rapid responses!

Best, M
