### ISSUE TITLE
glumpy doesn't work without glfw

### ISSUE THREAD

**Issue by rossant** [glumpy/glumpy#58]
whereas the documentation says that `You only need to have one of these packages, no need to install them all !`
glfw can be a pain to install

**Comment by rougier** [comment]
But it should work with glut only, no ?

**Comment by tjragan** [comment]
I've had this same problem.  I've got PyQt4 install and working fine.  Here's the traceback:

```python
In [1]: import glumpy
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-8b7a301dd2d3> in <module>()
----> 1 import glumpy

/Users/tjr22/bin/anaconda/lib/python3.5/site-packages/glumpy/__init__.py in <module>()
      6 __version__ = "2.0"
      7
----> 8 from . import app
      9 from . import api
     10 from . import gloo

/Users/tjr22/bin/anaconda/lib/python3.5/site-packages/glumpy/app/__init__.py in <module>()
     15 from glumpy import gl
     16 from glumpy.log import log
---> 17 from glumpy.ext.inputhook import inputhook_manager, stdin_ready
     18 from glumpy.app.window import backends
     19

/Users/tjr22/bin/anaconda/lib/python3.5/site-packages/glumpy/ext/__init__.py in <module>()
      4 # Distributed under the (new) BSD License. See LICENSE.txt for more info.
      5 # -----------------------------------------------------------------------------
----> 6 from . import glfw
      7 from . import freetype
      8

/Users/tjr22/bin/anaconda/lib/python3.5/site-packages/glumpy/ext/glfw.py in <module>()
     58 # Else, we failed and exit
     59 if _glfw_file is None:
---> 60     raise OSError('GLFW library not found')
     61
     62 # Load it

OSError: GLFW library not found
```

**Comment by rougier** [comment]
Should be fixed now.

**Comment by mryellow** [comment]
@rougier This continues to be an issue elsewhere.

```
   self.window = glumpy.Window(width, height)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/__init__.py", line 150, in __new__
    backend = use(name)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/__init__.py", line 116, in use
    importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/glumpy/app/window/backends/backend_glfw.py", line 82, in <module>
    from glumpy.ext import glfw
  File "/usr/local/lib/python2.7/dist-packages/glumpy/ext/glfw.py", line 60, in <module>
    raise OSError('GLFW library not found')
OSError: GLFW library not found
```

**Comment by mryellow** [comment]
Scratch that. Appears `apt` crashed when used with GUI and they never actually got installed.

**Comment by rougier** [comment]
You mean libglfw is not installed ?

**Comment by mryellow** [comment]
Yeah it really wasn't installed although I thought it had been. I used the GUI instead of `apt-get` and it must have crashed in the background rather than installing it. Installed from CLI and made it past that error.

Wasn't quite the layout for my use-case, I've moved back to using pyglet and managed to figure out the array shape and casting.

**Comment by rougier** [comment]
Ok, then I can close the issue?

**Comment by mryellow** [comment]
Go for it. Thanks.
