### ISSUE TITLE
glumpy mac os x el capitain: AttributeError

### ISSUE THREAD

**Issue by federicohyo** [glumpy/glumpy#59]
Hi there,
I am trying to run a code that runs under linux but does not run under mac os x.

the code is the following:
### CODE
import numpy, glumpy
import threading
...
Z = numpy.zeros([ydim,xdim]).astype(numpy.float32)
window = glumpy.Window(512, 512)
I = glumpy.Image(numpy.flipud(Z), interpolation='nearest', cmap=glumpy.colormap.Grey_r, vmin=-1, vmax=1)
...

#ERROR 

Federicos-MacBook-Air: federicocorradi$ python program.py -b glfw
2015-11-06 21:18:22.465 Python[34221:759490] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/by/sd176yq13ql_yfdz_d5sby_40000gn/T/org.python.python.savedState
[i] Using GLFW (GL 2.1)
Traceback (most recent call last):
  File "program.py", line 24, in <module>
    I = glumpy.Image(numpy.flipud(Z), interpolation='nearest', cmap=glumpy.colormap.Grey_r, vmin=-1, vmax=1)
AttributeError: 'module' object has no attribute 'Image'

or with sdl

Federicos-MacBook-Air: federicocorradi$ python program.py -b sdl2
[w] Backend (<module 'SDL2' from '/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/backends/backend_sdl2.pyc'>) not available
2015-11-06 21:21:03.293 Python[34230:760284] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/by/sd176yq13ql_yfdz_d5sby_40000gn/T/org.python.python.savedState
[i] Using GLFW (GL 2.1)
Traceback (most recent call last):
  File "program.py", line 24, in <module>
    I = glumpy.Image(numpy.flipud(Z), interpolation='nearest', cmap=glumpy.colormap.Grey_r, vmin=-1, vmax=1)
AttributeError: 'module' object has no attribute 'Image'

any ideas? I think I have installed all the required packages..

**Comment by rougier** [comment]
This might be the old version fo glumpy. You should try the github version.

**Comment by federicohyo** [comment]
Federicos-MacBook-Air:Downloads federicocorradi$ git clone https://github.com/glumpy/glumpy.git
Cloning into 'glumpy'...
remote: Counting objects: 5227, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 5227 (delta 3), reused 0 (delta 0), pack-reused 5211
Receiving objects: 100% (5227/5227), 7.91 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (3758/3758), done.
Checking connectivity... done.
....

glumpy 1.0.5 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg
Processing dependencies for glumpy==1.0.5
Searching for Cython==0.23.4
Best match: Cython 0.23.4
Processing Cython-0.23.4-py2.7-macosx-10.10-x86_64.egg
Cython 0.23.4 is already the active version in easy-install.pth
Installing cython script to /usr/local/bin
Installing cygdb script to /usr/local/bin
Installing cythonize script to /usr/local/bin

then sudo python setup.py install ....
### INSTALL
Using /usr/local/lib/python2.7/site-packages/Cython-0.23.4-py2.7-macosx-10.10-x86_64.egg
Searching for triangle==2015.3.28
Best match: triangle 2015.3.28
Processing triangle-2015.3.28-py2.7-macosx-10.10-x86_64.egg
triangle 2015.3.28 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/triangle-2015.3.28-py2.7-macosx-10.10-x86_64.egg
Searching for numpy==1.10.1
Best match: numpy 1.10.1
Adding numpy 1.10.1 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for glumpy==1.0.5
### END INSTALL

but still the same error

Federicos-MacBook-Air: federicocorradi$ python program.py 
2015-11-07 10:17:34.765 Python[4847:1489607] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/by/sd176yq13ql_yfdz_d5sby_40000gn/T/org.python.python.savedState
[i] Using GLFW (GL 2.1)
Traceback (most recent call last):
  File "program.py", line 24, in <module>
    I = glumpy.Image(numpy.flipud(Z), interpolation='nearest', cmap=glumpy.colormap.Grey_r, vmin=-1, vmax=1)
AttributeError: 'module' object has no attribute 'Image'

is this the older version of glumpy?

**Comment by rougier** [comment]
Ok, I think your program.py comes from an older version. Do the examples in glumpy/examples run ok ?

**Comment by federicohyo** [comment]
Here it is what happens when I try the examples...

### EXAMPLE VORONOI

Federicos-MacBook-Air:examples federicocorradi$ python voronoi.py 
2015-11-07 13:52:43.295 Python[5124:1515426] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/by/sd176yq13ql_yfdz_d5sby_40000gn/T/org.python.python.savedState
[i] HiDPI detected, fixing window size
[i] Using GLFW (GL 2.1)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "voronoi.py", line 112, in <module>
    app.run()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "voronoi.py", line 61, in on_draw
    with borders:
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/graphics/filter.py", line 151, in __enter__
    self._framebuffers[0].activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/framebuffer.py", line 390, in _activate
    self._attach()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/framebuffer.py", line 419, in _attach
    buffer.activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/texture.py", line 314, in _update
    self._cpu_format, self.gtype, self)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)
  File "wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)
  File "wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)
  File "wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)
  File "/usr/local/lib/python2.7/site-packages/OpenGL/GL/images.py", line 457, in __call__
    return arrayType.asArray( arg )
  File "arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)
  File "arraydatatype.pyx", line 57, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)
TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[ 0.,  0.,  0.],\n        [ 0.,  0.,  0) registered", <OpenGL.GL.images.ImageInputConverter object at 0x1078c2ed0>)

##EXAMPLE geom-path

Federicos-MacBook-Air:examples federicocorradi$ python geom-path.py 
2015-11-07 13:53:18.882 Python[5134:1515844] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/by/sd176yq13ql_yfdz_d5sby_40000gn/T/org.python.python.savedState
[i] Using GLFW (GL 2.1)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "geom-path.py", line 350, in <module>
    app.run()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "geom-path.py", line 344, in on_draw
    program.draw(gl.GL_LINE_STRIP_ADJACENCY_EXT, I)
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/program.py", line 501, in draw
    self.activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/program.py", line 353, in _activate
    attribute.activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/variable.py", line 323, in _activate
    self.data.activate()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/site-packages/glumpy-1.0.5-py2.7-macosx-10.11-x86_64.egg/glumpy/gloo/buffer.py", line 75, in _update
    gl.glBufferSubData(self.target, offset, nbytes, data)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1201)
  File "/usr/local/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_1_5.py", line 122, in glBufferSubData
    data = ArrayDatatype.asArray( data )
  File "arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)
  File "arraydatatype.pyx", line 57, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)
TypeError: No array-type handler for type <class 'glumpy.gloo.buffer.VertexBuffer'> (value: VertexBuffer([  0,  96,  11,  68,   0,   0, 200,  ) registered

**Comment by rougier** [comment]
I've already get this error and it seems the OpenGL_accelerate module is responsible for the trouble. If you remove, it should work.

**Comment by federicohyo** [comment]
I removed pyopengl_accellerate with the command:

$ pip uninstall PyOpenGL-accelerate

now all examples are working, except my old code, which used glumpy.Image. However I'll have to re-code it anywyas.

thanks for your support.

**Comment by rougier** [comment]
Thanks for reporting the issue.

**Comment by sachinjm** [comment]
I am having glumpy 1.0.6 with python 3.5. I am facing same error as AttributeError: module 'glumpy' has no attribute 'colormap'. Tried running test_rbm.py from https://github.com/trunghlt/pyRBM and followed instructions from https://github.com/glumpy/glumpy in install glumpy.

Running on windows 7

Please help me 
Sachin
