### ISSUE TITLE
OpenGL / GLUT problem

### ISSUE THREAD

**Issue by untereiner** [glumpy/glumpy#7]
```
python examples/app-backend.py
[w] Cannot set error on copy on GPU copy
Traceback (most recent call last):
  File "examples/app-backend.py", line 7, in <module>
    from glumpy import app
  File "/home/untereiner/lib/python2.7/site-packages/glumpy/__init__.py", line 8, in <module>
    from . app import run
  File "/home/untereiner/lib/python2.7/site-packages/glumpy/app/__init__.py", line 17, in <module>
    from glumpy.ext.inputhook import inputhook_manager, stdin_ready
  File "/home/untereiner/lib/python2.7/site-packages/glumpy/ext/__init__.py", line 6, in <module>
    from . import glfw
  File "/home/untereiner/lib/python2.7/site-packages/glumpy/ext/glfw.py", line 60, in <module>
    raise OSError('GLFW library not found')
OSError: GLFW library not found
```

How can I use a glut backend for linux ? 
The backend osxfreeglut doesn't seem to work

PyOpenGL==3.1.0
PyOpenGL-accelerate==3.1.0
glumpy==latest git version
numpy==1.8.2

**Comment by jvtrudel** [comment]
I wanted to explore the Glumpy's examples to follow the next sprint of the vispy project.

But as @untereiner did, I got this weird error:

   [w] Cannot set error on copy on GPU copy
   [i] Using SDL2 (GL 2.1)
   [i] Running at 60 frames/second
   /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py:374: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
    baseOperation(program, index, length, namelen, size, gl_type, name)
    Traceback (most recent call last):
    ...

I tested it with backends glfw, sdl2, pyside, pyglet and  osxglut. It gives me about the same error message. 

I installed my backends using Macports and the GL's version seems to be 2.0. But glumpy specify version 2.1 . 

Could it be the problem? How to solve it?

**Comment by jvtrudel** [comment]
I uninstalled Macports' pyOpenGL and reinstalled it with pip... I get the same error.

**Comment by rossant** [comment]
might be a driver problem (but I have no experience with OS X). @rougier will be more helpful hopefully...

**Comment by jvtrudel** [comment]
The first error comes from OpenGL.arrays ...

    ----> 8 from OpenGL.arrays import numpymodule
    ...
    ipdb> n
    TypeError: "can't set attributes of built-in/extension type 'OpenGL_accelerate.numpy_formathandler.NumpyHandler'"
    > /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gl.py(11)<module>()
         10 try:
    ---> 11     numpymodule.NumpyHandler.ERROR_ON_COPY = True
    ...
    ---> 12 except TypeError:
         13     log.warn("Cannot set error on copy on GPU copy")

**Comment by jvtrudel** [comment]
If it is a driver problem, could I run vispy? I can.

**Comment by rossant** [comment]
It probably depends... VisPy and Glumpy do not use exactly the same GL bindings AFAIK.

**Comment by rougier** [comment]
I use PyOpenGL bindings and it seems there is a problem with it.
The exception is raised from https://github.com/glumpy/glumpy/blob/master/glumpy/gl.py (line 10-13)

These lines are supposed to tell PyOpenGL to not copy array before uploading them to GPU. I try to ensure this is always the case and this setting is a safeguard. It's ok to comment these lines if needed.

But it should continue anyway. Are there any other traceback ?

**Comment by jvtrudel** [comment]
Could I replace PyOpenGL by something else?

I commented the lines in gl.py.
Here's the trace back I got:

    [i] Running at 60 frames/second
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py:374: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
      baseOperation(program, index, length, namelen, size, gl_type, name)
    TypeError: TypeErro...19cffd0>)
    > /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py(98)<module>()
         96 program['transform'] = transform
         97 window.attach(transform)
    ---> 98 app.run()

It seems to be related to arrays.GL_CONSTANT_TO_ARRAY_TYPE at line 456 of ~/OpenGL/GL/images.pyc

Unfortunately, I don't understand and I can't go further by myself.
Here's the full debugging traceback:

    In [1]: %run -d isocurves.py
    *** Blank or comment
    *** Blank or comment
    *** Blank or comment
    *** Blank or comment
    *** Blank or comment
    *** Blank or comment
    *** Blank or comment
    NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
    > /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py(7)<module>()
          6 # -----------------------------------------------------------------------------
    ----> 7 import numpy as np
          8 from glumpy import app, gl, gloo, data
    
    ipdb> b 98
    Breakpoint 1 at /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py:98
    ipdb> c
    [i] HiDPI detected, fixing window size
    [i] Using GLFW (GL 2.1)
    > /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py(98)<module>()
         96 program['transform'] = transform
         97 window.attach(transform)
    1--> 98 app.run()
    
    ipdb> s
    --Call--
    > /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/__init__.py(281)run()
        280 # --------------------------------------------------------------------- run ---
    --> 281 def run(clock=None, framerate=None, interactive=None,
        282         duration = sys.maxint, framecount = sys.maxint):
    
    ipdb> n
    > /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/__init__.py(301)run()
        300 
    --> 301     clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
        302     options = parser.get_options()
    
    ipdb> c
    [i] Running at 60 frames/second
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py:374: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
      baseOperation(program, index, length, namelen, size, gl_type, name)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in safe_execfile(self, fname, *where, **kw)
       2632                 py3compat.execfile(
       2633                     fname, glob, loc,
    -> 2634                     self.compile if kw['shell_futures'] else None)
       2635             except SystemExit as status:
       2636                 # If the call was made with 0 or None exit status (sys.exit(0)
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/utils/py3compat.pyc in execfile(fname, glob, loc, compiler)
        215             where = [ns for ns in [glob, loc] if ns is not None]
        216             if compiler is None:
    --> 217                 builtin_mod.execfile(filename, *where)
        218             else:
        219                 scripttext = builtin_mod.open(fname).read().rstrip() + '\n'
    
    /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py in <module>()
         96 program['transform'] = transform
         97 window.attach(transform)
    ---> 98 app.run()
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/__init__.pyc in run(clock, framerate, interactive, duration, framecount)
        299     global __running__
        300 
    --> 301     clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
        302     options = parser.get_options()
        303 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/__init__.pyc in __init__(clock, framerate, backend)
        259 
        260         # Dispatch an initial resize event
    --> 261         window.dispatch_event('on_resize', window._width, window._height)
        262 
        263     return __clock__
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
        377             except TypeError:
        378                 self._raise_dispatch_exception(
    --> 379                     event_type, args, getattr(self, event_type))
        380 
        381         if invoked:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
        373             try:
        374                 invoked = True
    --> 375                 if getattr(self, event_type)(*args):
        376                     return EVENT_HANDLED
        377             except TypeError:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/window.pyc in on_resize(self, width, height)
        191         """" Default resize handler that set viewport """
        192         gl.glViewport(0, 0, width, height)
    --> 193         self.dispatch_event('on_draw', 0.0)
        194         self.swap()
        195 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
        366                         return EVENT_HANDLED
        367                 except TypeError:
    --> 368                     self._raise_dispatch_exception(event_type, args, handler)
        369 
        370 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/app/window/event.pyc in dispatch_event(self, event_type, *args)
        363                 try:
        364                     invoked = True
    --> 365                     if handler(*args):
        366                         return EVENT_HANDLED
        367                 except TypeError:
    
    /Users/manitou6/Documents/forks/glumpy/examples/isocurves.py in on_draw(dt)
         69 def on_draw(dt):
         70     window.clear()
    ---> 71     program.draw(gl.GL_TRIANGLES, I)
         72 
         73 @window.event
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/program.pyc in draw(self, mode, indices)
        497         """
        498 
    --> 499         self.activate()
        500         attributes = self._attributes.values()
        501 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/globject.pyc in activate(self)
         88             self._need_create = False
         89 
    ---> 90         self._activate()
         91 
         92         if self.need_setup:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/program.pyc in _activate(self)
        347         for uniform in self._uniforms.values():
        348             if uniform.active:
    --> 349                 uniform.activate()
        350 
        351         for attribute in self._attributes.values():
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/globject.pyc in activate(self)
         88             self._need_create = False
         89 
    ---> 90         self._activate()
         91 
         92         if self.need_setup:
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/variable.pyc in _activate(self)
        215                 log.debug("GPU: Active texture is %d" % self._texture_unit)
        216                 gl.glActiveTexture(gl.GL_TEXTURE0 + self._texture_unit)
    --> 217                 self.data.activate()
        218 
        219     def _update(self):
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/globject.pyc in activate(self)
         95 
         96         if self.need_update:
    ---> 97             self._update()
         98             self._need_update = False
         99 
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glumpy-1.0.3-py2.7-macosx-10.10-x86_64.egg/glumpy/gloo/texture.pyc in _update(self)
        312             gl.glBindTexture(self._target, self.handle)
        313             gl.glTexSubImage2D(self.target, 0, x, y, width, height,
    --> 314                                self._cpu_format, self.gtype, self)
        315             gl.glBindTexture(self._target, self.handle)
        316 
    
    latebind.pyx in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)()
    
    wrapper.pyx in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)()
    
    wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)()
    
    wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)()
    
    wrapper.pyx in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)()
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/OpenGL/GL/images.pyc in __call__(self, arg, baseOperation, pyArgs)
        455         type = pyArgs[ self.typeIndex ]
        456         arrayType = arrays.GL_CONSTANT_TO_ARRAY_TYPE[ images.TYPE_TO_ARRAYTYPE[ type ] ]
    --> 457         return arrayType.asArray( arg )
        458 #       def cResolver( self, array ):
        459 #               return array
    
    arraydatatype.pyx in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)()
    
    arraydatatype.pyx in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)()
    
    TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[ 0.38643736],\n        [ 0.38621724],\n) registered", <OpenGL.GL.images.ImageInputConverter object at 0x10d36ced0>)

**Comment by rougier** [comment]
Do you know what is your PyOpenGL version ? 
If not latest, can you upgrade it ?

**Comment by jvtrudel** [comment]
I had PyOpenGL 3.1.0 . I tried with version 3.1.1a1. But I still have the same annoying error...

Anyway, maybe I should stop their and put energy directly on vispy?

**Comment by rougier** [comment]
Yes, if vispy works it would be best. And most glumpy demo will eventually migrate to vispy.

**Comment by federicohyo** [comment]
I have the following error when trying to run the examples.
 - Ubuntu 14.04
- PyOpenGL-3.1.1a1
- PyOpenGL-accelerate-3.1.1a1
- glfw-3.1.1
- cython 0.20.1post0
- Pillow 3.0

federico@zappatore:~/iniLabs/3rdparty/glumpy/examples$ python collection-update.py --backend glfw
[w] Cannot set error on copy on GPU copy
[i] Using GLFW (GL 4.5)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "collection-update.py", line 129, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "collection-update.py", line 98, in on_draw
    lines.draw()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/graphics/collections/collection.py", line 210, in draw
    program.draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/program.py", line 501, in draw
    self.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/program.py", line 349, in _activate
    uniform.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/variable.py", line 217, in _activate
    self.data.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/texture.py", line 314, in _update
    self._cpu_format, self.gtype, self)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)
  File "wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)
  File "wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)
  File "wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)
  File "/usr/local/lib/python2.7/dist-packages/PyOpenGL-3.1.1a1-py2.7.egg/OpenGL/GL/images.py", line 458, in __call__
    return arrayType.asArray( arg )
  File "arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)
  File "arraydatatype.pyx", line 57, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)
TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[  0.70287275,   0.75804245,   0.62404) registered", <OpenGL.GL.images.ImageInputConverter object at 0x7fa531f6ba90>)
federico@zappatore:~/iniLabs/3rdparty/glumpy/examples$ python collection-update.py --backend osxglut
[w] Cannot set error on copy on GPU copy
[w] Backend (<module 'OSX GLUT' from '/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/backends/backend_osxglut.pyc'>) not available
[i] Using GLFW (GL 4.5)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "collection-update.py", line 129, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "collection-update.py", line 98, in on_draw
    lines.draw()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/graphics/collections/collection.py", line 210, in draw
    program.draw(mode)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/program.py", line 501, in draw
    self.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/program.py", line 349, in _activate
    uniform.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/variable.py", line 217, in _activate
    self.data.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/texture.py", line 314, in _update
    self._cpu_format, self.gtype, self)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)
  File "wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)
  File "wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)
  File "wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)
  File "/usr/local/lib/python2.7/dist-packages/PyOpenGL-3.1.1a1-py2.7.egg/OpenGL/GL/images.py", line 458, in __call__
    return arrayType.asArray( arg )
  File "arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)
  File "arraydatatype.pyx", line 57, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)
TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[ 0.84089476,  0.69332749,  0.8055411 ) registered", <OpenGL.GL.images.ImageInputConverter object at 0x7fa505e06a90>)


all of the examples are not working for me.

federico@zappatore:~/iniLabs/3rdparty/glumpy/examples$ python voronoi.py 
[w] Cannot set error on copy on GPU copy
[i] Using GLFW (GL 4.5)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "voronoi.py", line 111, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 301, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/__init__.py", line 261, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/window.py", line 197, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "voronoi.py", line 61, in on_draw
    with borders:
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/graphics/filter.py", line 151, in __enter__
    self._framebuffers[0].activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 90, in activate
    self._activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/framebuffer.py", line 390, in _activate
    self._attach()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/framebuffer.py", line 419, in _attach
    buffer.activate()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/globject.py", line 97, in activate
    self._update()
  File "/usr/local/lib/python2.7/dist-packages/glumpy-1.0.5-py2.7-linux-x86_64.egg/glumpy/gloo/texture.py", line 314, in _update
    self._cpu_format, self.gtype, self)
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6294)
  File "wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call (src/wrapper.c:4241)
  File "wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3601)
  File "wrapper.pyx", line 122, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call (src/wrapper.c:3520)
  File "/usr/local/lib/python2.7/dist-packages/PyOpenGL-3.1.1a1-py2.7.egg/OpenGL/GL/images.py", line 458, in __call__
    return arrayType.asArray( arg )
  File "arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray (src/arraydatatype.c:4221)
  File "arraydatatype.pyx", line 57, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup (src/arraydatatype.c:2230)
TypeError: ("No array-type handler for type <class 'glumpy.gloo.texture.Texture2D'> (value: Texture2D([[[ 0.,  0.,  0.],\n        [ 0.,  0.,  0) registered", <OpenGL.GL.images.ImageInputConverter object at 0x7fcc0ed01910>)

The only code that works for me is the following (which is not much appealing):

from glumpy import app
window = app.Window(512,512)
@window.event
def on_draw(dt):
    window.clear()
app.run()

Do I miss something?

**Comment by rougier** [comment]
Can you open a new issue ?
