### ISSUE TITLE
earth.py example broken

### ISSUE THREAD

**Issue by dopplershift** [glumpy/glumpy#71]
It looks like the `earth.py` example was broken by the move to `Arcball` from `Trackball`. This is the error I get (Python 3.5):
```
Traceback (most recent call last):
  File "earth.py", line 63, in <module>
    earth['transform'] = transform
  File "/Users/rmay/repos/glumpy/glumpy/gloo/program.py", line 328, in __setitem__
    snippet.attach(self)
  File "/Users/rmay/repos/glumpy/glumpy/transforms/transform.py", line 73, in attach
    self.dispatch_event("on_attach", program)
  File "/Users/rmay/repos/glumpy/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/Users/rmay/repos/glumpy/glumpy/transforms/arcball.py", line 178, in on_attach
    self["view"] = self._view
  File "/Users/rmay/repos/glumpy/glumpy/transforms/transform.py", line 57, in __setitem__
    Snippet.__setitem__(self, key, value)
  File "/Users/rmay/repos/glumpy/glumpy/gloo/snippet.py", line 601, in __setitem__
    raise IndexError(error)
IndexError: Snippet does not have such key ("arcball_view")
```
If I just change `Arcball` to `Trackball` it works.

I noticed that the `Arcball` class is looking for `arcball.glsl`, which is not found anywhere in the repository. It looks like the code for `library.get()` will return the filename if a shader is not found--likely resulting in the code trying to use that filename as the shader source, causing the binding failure.

**Comment by rougier** [comment]
Oh thanks, I forgot to add the shader code...
And the library.get() returning the filename is not really a good option. The goadl was to seamlessly pass a shader code or the content of a filename. I need to work on that.

**Comment by rougier** [comment]
@dopplershift Do you confirm the fix or is it still broken ?

**Comment by dopplershift** [comment]
Fixed. Thanks!
