### ISSUE TITLE
Change backend of glumpy in OSX

### ISSUE THREAD

**Issue by MetaDev** [glumpy/glumpy#78]
Whenever I try to use the "osxglut" backend I get,

[i] Using OSX GLUT (GL 2.1)
INFO:glumpy:[i] Using OSX GLUT (GL 2.1)
[i] Running at 60 frames/second
INFO:glumpy:[i] Running at 60 frames/second
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

The GLFW backend works, but if I try to target a different openGL version I get:

[w] b'The GLFW library is not initialized'
WARNING:glumpy:[w] b'The GLFW library is not initialized'

---------------------------------------

Python 3.5.1 64bits, Qt 5.5.0, PyQt5 5.5 on Darwin

dependencies:
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
numpy >=1.7     :  1.11.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.0.0 (OK)
pyflakes >=0.6.0:  1.0.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by rougier** [comment]
Could you post a minimal script ?

**Comment by MetaDev** [comment]
after re-running the same script, I get a different error now. It could be due to some changes in packages I updated recently (Tkinter ?). 

script:

from glumpy import app
app.use("glfw",major=3,minor=3,profile="core")

window = app.Window()

@window.event
def on_draw(dt):
    window.clear()

app.run()

out:

[i] HiDPI detected, fixing window size
INFO:glumpy:[i] HiDPI detected, fixing window size
[i] Using GLFW (GL 4.1)
INFO:glumpy:[i] Using GLFW (GL 4.1)
[i] Running at 60 frames/second
INFO:glumpy:[i] Running at 60 frames/second
Traceback (most recent call last):

  File "<ipython-input-1-fe22352b4c03>", line 1, in <module>
    runfile('/Users/Harald/Cloud Workspace/Art projects/Python/Hypergenerator/lib_test/glumpy_test.py', wdir='/Users/Harald/Cloud Workspace/Art projects/Python/Hypergenerator/lib_test')

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 841, in runfile
    execfile(filename, namespace)

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 103, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/Harald/Cloud Workspace/Art projects/Python/Hypergenerator/lib_test/glumpy_test.py", line 10, in <module>
    app.run()

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/glumpy/app/__init__.py", line 302, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/glumpy/app/__init__.py", line 244, in __init__
    gl.glEnable(gl.GL_POINT_SPRITE)

  File "/Users/Harald/anaconda/lib/python3.5/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,

GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glEnable,
	cArguments = (GL_POINT_SPRITE,)
)

**Comment by rougier** [comment]
`gl.glEnable(gl.GL_POINT_SPRITE)` is necessary for GL < 3.0 I think. I shoudl add a specific test for knowing what is the current context before activating or not GL_POINT_SPRITE.
