### ISSUE TITLE
OpenGL 3.2 core profile error on Mac OS X

### ISSUE THREAD

**Issue by landersson** [glumpy/glumpy#79]
Hi, I just tried enabling OpenGL 3.2 core profile by adding the following snippet to the basic 'quad-simple.py' example:

```
from glumpy import app

config = app.configuration.Configuration()
config.major_version = 3
config.minor_version = 2
config.profile = "core"
window = app.Window(config=config)
```

This results in the following error on my retina macbook running osx 10.11:

```
i] HiDPI detected, fixing window size
[i] Using GLFW (GL 4.1)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "test_glumpy.py", line 44, in <module>
    app.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/glumpy/app/__init__.py", line 302, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/glumpy/app/__init__.py", line 244, in __init__
    gl.glEnable(gl.GL_POINT_SPRITE)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
    err = 1280,
    description = b'invalid enumerant',
    baseOperation = glEnable,
    cArguments = (GL_POINT_SPRITE,)
)
```

I tried commenting out the statement `gl.glEnable(gl.GL_POINT_SPRITE)` but then I get the following error:

```
Error in Vertex shader 2 (<string>)
 -> '' :  version '120' is not supported

 000 #define _GLUMPY__VERTEX_SHADER__
 001 // --- Snippets code : start --- //
 002 // --- Snippets code : end --- // 
............
```

**Comment by rougier** [comment]
Thanks for the report. The `version 120` is inserted from the shader class and is not compatible with 3.2 context. I should make a specific test for the current context. Problem is that some shader code won't work with newer GL shader specs and I've currently no solution. Is a 3.2 context mandatory in your case ?

**Comment by landersson** [comment]
I don't think a 3.2 context is necessarily mandatory. I wanted to run a shader that used the statement `out uvec4`, which is seems to be available only in GLSL 130 and above.

**Comment by rougier** [comment]
Do you have a pointer on this shader ?

**Comment by landersson** [comment]
I'm afraid I don't know what you mean by pointer on a shader... (unfortunately I currently have very little experience writing shaders)

The shader that I wanted to run was from one of the CUDA/OpenGL interoperability examples in the CUDA SDK:
```
#version 130
out uvec4 FragColor;
void main()
{
    FragColor = uvec4(gl_Color.xyz * 255.0, 255.0);
}
```

**Comment by rougier** [comment]
I meant a link to the shader code, sorry. But I  suspect this shader code is mixing "old" OpenGL code with new shader code. Without the context, it's hard to say.

Did you have a look at the different glumpy examples ? If you're inexperienced with shaders, you can start playing with https://github.com/glumpy/glumpy/blob/master/examples/gloo-quad.py

**Comment by landersson** [comment]
Thanks, I definitively hope to play more with GL shaders via glumpy when I find a bit more spare time.

**Comment by rougier** [comment]
Ok, can I close th issue then ?

**Comment by landersson** [comment]
It would be nice to be able to enable more modern OpenGL features under glumpy at some point. I'm sure there are many higher priority issues to deal with at the moment though, so certainly feel free to close this.

**Comment by rougier** [comment]
I agree, it's on the todo list but I lack some free time right now.

**Comment by autosquid** [comment]
Hi, any progress on this? I am expecting more modern GL features, and that is the reason I turn to glumpy from vispy. 

Back to the problem, I am wondering where the difficulty lies in enabling both old and modern GL?

**Comment by rougier** [comment]
It depends on what you call old and modern. For the fixed pipeline, it is deprecated and it's not worth the effort since we cannot much with this old API (and this would require a full rewrite).

Concerning the different shader versions, there is no technical difficulty, I just lack time right now. The exact problem comes from the fact I insert explicitly `#version 120` in the generated shaders and this should be done only when necessary. Could you open a specific issue on this problem?

**Comment by autosquid** [comment]
Thanks for your explaination. I removed the hard-coded "#version 120" and add GLSL version info into the shader sources (, and make other little fixes such as hacks with "attribute" and "in"). However, there would still problems. I will open another issue.
