### ISSUE TITLE
TypeError in matplotlib example 3

### ISSUE THREAD

**Issue by lourenko** [glumpy/glumpy#97]
Here's the traceback when I tried to run the **examples/matplotlib-3.py** using python3.5 in kubuntu zesty:

```[i] Using GLFW (GL 4.5)
[i] Running at 60 frames/second
Traceback (most recent call last):
  File "matplotlib-3.py", line 98, in <module>
    figure.show()
  File "/usr/local/lib/python3.5/dist-packages/glumpy/api/matplotlib/figure.py", line 26, in show
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/__init__.py", line 302, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/__init__.py", line 262, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/window.py", line 219, in on_resize
    self.dispatch_event('on_draw', 0.0)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 387, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 384, in dispatch_event
    if handler(*args):
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/viewport.py", line 477, in on_draw
    child.dispatch_event("on_draw", dt)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 398, in dispatch_event
    event_type, args, getattr(self, event_type))
  File "/usr/local/lib/python3.5/dist-packages/glumpy/app/window/event.py", line 394, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/usr/local/lib/python3.5/dist-packages/glumpy/api/matplotlib/axes.py", line 101, in on_draw
    drawable.draw()
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/collections/collection.py", line 251, in draw
    collection._update()
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/collections/base_collection.py", line 517, in _update
    texture = texture.reshape(shape[0],shape[1],int(4))
TypeError: 'float' object cannot be interpreted as an integer
```

The example work when I replace the /usr/local/lib/python3.5/dist-packages/glumpy/graphics/collections/base_collection.py", line 517 by 

> texture = texture.reshape(int(shape[0]),int(shape[1]),4).

**Comment by rougier** [comment]
I think this is a type problem, can you try `texture = texture.reshape(int(shape[0]),int(shape[1]),int(4))` instead ?

**Comment by lourenko** [comment]
As I said previously, I just tried `texture = texture.reshape(int(shape[0]),int(shape[1]),4)` and it works. Its again another *type* problem, from python2 to python3 different syntaxes.

**Comment by rougier** [comment]
I think numpy is also less permissive. Can you make a PR ?
