### ISSUE TITLE
TypeError in Hello world example

### ISSUE THREAD

**Issue by lourenko** [glumpy/glumpy#98]
Here's the traceback when I tried to run the examples/hello-world.py using python3.5 in kubuntu zesty:

```
[i] Using GLFW (GL 4.5)
Traceback (most recent call last):
  File "hello-world.py", line 22, in <module>
    origin=(x,y,z), color=(1,1,1,1))
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/collections/agg_glyph_collection.py", line 75, in append
    V, I = self.bake(text, font, anchor_x, anchor_y)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/collections/agg_glyph_collection.py", line 127, in bake
    glyph = font[charcode]
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/text/agg_font.py", line 32, in __getitem__
    self.load('%c' % charcode)
  File "/usr/local/lib/python3.5/dist-packages/glumpy/graphics/text/agg_font.py", line 82, in load
    texture = self.atlas[y:y+h,x:x+w]
  File "/usr/local/lib/python3.5/dist-packages/glumpy/gloo/gpudata.py", line 116, in __getitem__
    Z = np.ndarray.__getitem__(self, key)
TypeError: slice indices must be integers or None or have an __index__ method
```

Any glue about I am made something wrong or this might be a bug?
Thanks anyway.

**Comment by rougier** [comment]
I think this comes from numpy that was accepting non integers indices before but this is no longer the case. Can you check `y`,`h`, `x` and `w` are integers  (or cast them into int to check this is the reason) ?

**Comment by lourenko** [comment]
I just checked and only `w` is a float. Replacing `w = width/3` with `w = width//3` in /usr/local/lib/python3.5/dist-packages/glumpy/graphics/text/agg_font.py", line 71, solves the problem.

**Comment by rougier** [comment]
Thanks! Can you make a PR ?
